name: benchmark-test
on: push
env:
  gh-pages-branch: fp/benchmark-gh-pages-test
jobs:
  query-benchmark:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Download previously built wrappers
        id: wrapper-cache
        uses: actions/cache@v2
        with:
          path: .\wrappers\build\Windows\
          # This needs to be changed to something meaningful
          key: wrap-all 
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@v5
        with:
          # Contains the list of packages and the triplet
          vcpkgArguments: '@${{ env.vcpkgResponseFile }}'
          vcpkgGitCommitId: ec6fe06e8da05a8157dc8581fa96b36b571c1bd5
          # If the cache key is the same, it does not execute
          appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}
        env:
          vcpkgResponseFile: '${{ github.workspace }}\.github\workflows\response_file.txt'
      - name: Build wrappers
        if: steps.wrapper-cache.outputs.cache-hit != 'true'
        run: .\wrappers\build.ps1 Windows -Configuration Release -Platforms Win32 -Toolchain "${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake"
    
