name: benchmark-test
on: push
jobs:
  string-benchmark:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@v5
        with:
          vcpkgArguments: '@${{ env.vcpkgResponseFile }}'
          vcpkgGitCommitId: ec6fe06e8da05a8157dc8581fa96b36b571c1bd5
          appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}
        env:
          vcpkgResponseFile: '${{ github.workspace }}\.github\workflows\response_file.txt'
      - name: Build wrappers
        run: .\wrappers\build.ps1 Windows -Configuration Debug -Platforms Win32 -Toolchain "${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake"
      - name: Run benchmarks
        run:  dotnet run -p .\Tests\PerformanceTests\ run -c Release --framework net5.0 -- -f QueryTests
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: .\Tests\PerformanceTests\BenchmarkDotNet.Artifacts\results

    
