name: benchmark-test
on: push
jobs:
  string-benchmark:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build wrappers
        run: .\wrappers\build.ps1 Windows -Configuration Debug -Platforms Win32
      - name: Run benchmarks
        run:  dotnet run -p .\Tests\PerformanceTests\ run -c Release --framework net5.0 -- -f QueryTests
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: .\Tests\PerformanceTests\BenchmarkDotNet.Artifacts\results

    
