name: main
"on":
  push:
    branches:
    - main
    - master
  pull_request: null
env:
  REALM_DISABLE_ANALYTICS: true
  DOTNET_NOLOGO: true
jobs:
  wrappers-gha:
    runs-on: macos-latest
    name: iOS Wrappers on GHA-hosted
    timeout-minutes: 45
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build wrappers
      run: ./wrappers/build-ios.sh --configuration=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION='ON'
  wrappers-intel:
    runs-on: macos-intel
    name: iOS Wrappers on Intel
    timeout-minutes: 45
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build wrappers
      run: ./wrappers/build-ios.sh --configuration=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION='ON'
  wrappers-m1:
    runs-on: macos-m1
    name: iOS Wrappers on M1
    timeout-minutes: 45
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build wrappers
      run: ./wrappers/build-ios.sh --configuration=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION='ON'
  wrappers-mbp:
    runs-on: macos-mbp
    name: iOS Wrappers on MBP
    timeout-minutes: 45
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build wrappers
      run: ./wrappers/build-ios.sh --configuration=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION='ON'
