name: test_action
on: push
jobs:
  install_vcpkg:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print stuff
        run: write-output "${{ github.workspace }}"
        shell: powershell
      - name: Print stuff 2
        run: write-output "${{ env.GITHUB_WORKSPACE }}"
        shell: powershell
      - name: Print stuff 3
        run: write-output "$GITHUB_WORKSPACE"
        shell: powershell        
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Restore from cache and run vcpkg
        uses: lukka/run-vcpkg@v5
        with:
          vcpkgArguments: '@${{ github.workspace }}\.github\workflows\response_file.txt'
          vcpkgGitCommitId: ec6fe06e8da05a8157dc8581fa96b36b571c1bd5

    
